/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadIndexRouteImport } from './routes/download/index'
import { Route as FoundIdIndexRouteImport } from './routes/found/$id/index'
import { Route as ChatConversationIdIndexRouteImport } from './routes/chat/conversation/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadIndexRoute = DownloadIndexRouteImport.update({
  id: '/download/',
  path: '/download/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundIdIndexRoute = FoundIdIndexRouteImport.update({
  id: '/found/$id/',
  path: '/found/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatConversationIdIndexRoute = ChatConversationIdIndexRouteImport.update({
  id: '/chat/conversation/$id/',
  path: '/chat/conversation/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download': typeof DownloadIndexRoute
  '/found/$id': typeof FoundIdIndexRoute
  '/chat/conversation/$id': typeof ChatConversationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadIndexRoute
  '/found/$id': typeof FoundIdIndexRoute
  '/chat/conversation/$id': typeof ChatConversationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/download/': typeof DownloadIndexRoute
  '/found/$id/': typeof FoundIdIndexRoute
  '/chat/conversation/$id/': typeof ChatConversationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/download' | '/found/$id' | '/chat/conversation/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/download' | '/found/$id' | '/chat/conversation/$id'
  id:
    | '__root__'
    | '/'
    | '/download/'
    | '/found/$id/'
    | '/chat/conversation/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadIndexRoute: typeof DownloadIndexRoute
  FoundIdIndexRoute: typeof FoundIdIndexRoute
  ChatConversationIdIndexRoute: typeof ChatConversationIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/': {
      id: '/download/'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/found/$id/': {
      id: '/found/$id/'
      path: '/found/$id'
      fullPath: '/found/$id'
      preLoaderRoute: typeof FoundIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/conversation/$id/': {
      id: '/chat/conversation/$id/'
      path: '/chat/conversation/$id'
      fullPath: '/chat/conversation/$id'
      preLoaderRoute: typeof ChatConversationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadIndexRoute: DownloadIndexRoute,
  FoundIdIndexRoute: FoundIdIndexRoute,
  ChatConversationIdIndexRoute: ChatConversationIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
