/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as PremiumIndexRouteImport } from './routes/premium/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as MessageIndexRouteImport } from './routes/message/index'
import { Route as HelpIndexRouteImport } from './routes/help/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ProfilePublicCodeIndexRouteImport } from './routes/profile/$publicCode/index'
import { Route as PremiumSuccessIndexRouteImport } from './routes/premium/success/index'
import { Route as PremiumCheckoutIndexRouteImport } from './routes/premium/checkout/index'
import { Route as OrganizationsSlugIndexRouteImport } from './routes/organizations/$slug/index'
import { Route as FoundIdIndexRouteImport } from './routes/found/$id/index'
import { Route as AccountBillingIndexRouteImport } from './routes/account/billing/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumIndexRoute = PremiumIndexRouteImport.update({
  id: '/premium/',
  path: '/premium/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageIndexRoute = MessageIndexRouteImport.update({
  id: '/message/',
  path: '/message/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePublicCodeIndexRoute = ProfilePublicCodeIndexRouteImport.update({
  id: '/profile/$publicCode/',
  path: '/profile/$publicCode/',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumSuccessIndexRoute = PremiumSuccessIndexRouteImport.update({
  id: '/premium/success/',
  path: '/premium/success/',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumCheckoutIndexRoute = PremiumCheckoutIndexRouteImport.update({
  id: '/premium/checkout/',
  path: '/premium/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsSlugIndexRoute = OrganizationsSlugIndexRouteImport.update({
  id: '/organizations/$slug/',
  path: '/organizations/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundIdIndexRoute = FoundIdIndexRouteImport.update({
  id: '/found/$id/',
  path: '/found/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBillingIndexRoute = AccountBillingIndexRouteImport.update({
  id: '/account/billing/',
  path: '/account/billing/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/': typeof AccountIndexRoute
  '/help/': typeof HelpIndexRoute
  '/message/': typeof MessageIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/premium/': typeof PremiumIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/account/billing/': typeof AccountBillingIndexRoute
  '/found/$id/': typeof FoundIdIndexRoute
  '/organizations/$slug/': typeof OrganizationsSlugIndexRoute
  '/premium/checkout/': typeof PremiumCheckoutIndexRoute
  '/premium/success/': typeof PremiumSuccessIndexRoute
  '/profile/$publicCode/': typeof ProfilePublicCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountIndexRoute
  '/help': typeof HelpIndexRoute
  '/message': typeof MessageIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/premium': typeof PremiumIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/account/billing': typeof AccountBillingIndexRoute
  '/found/$id': typeof FoundIdIndexRoute
  '/organizations/$slug': typeof OrganizationsSlugIndexRoute
  '/premium/checkout': typeof PremiumCheckoutIndexRoute
  '/premium/success': typeof PremiumSuccessIndexRoute
  '/profile/$publicCode': typeof ProfilePublicCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account/': typeof AccountIndexRoute
  '/help/': typeof HelpIndexRoute
  '/message/': typeof MessageIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/premium/': typeof PremiumIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/account/billing/': typeof AccountBillingIndexRoute
  '/found/$id/': typeof FoundIdIndexRoute
  '/organizations/$slug/': typeof OrganizationsSlugIndexRoute
  '/premium/checkout/': typeof PremiumCheckoutIndexRoute
  '/premium/success/': typeof PremiumSuccessIndexRoute
  '/profile/$publicCode/': typeof ProfilePublicCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/'
    | '/help/'
    | '/message/'
    | '/organizations/'
    | '/premium/'
    | '/sign-in/'
    | '/sign-up/'
    | '/account/billing/'
    | '/found/$id/'
    | '/organizations/$slug/'
    | '/premium/checkout/'
    | '/premium/success/'
    | '/profile/$publicCode/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/help'
    | '/message'
    | '/organizations'
    | '/premium'
    | '/sign-in'
    | '/sign-up'
    | '/account/billing'
    | '/found/$id'
    | '/organizations/$slug'
    | '/premium/checkout'
    | '/premium/success'
    | '/profile/$publicCode'
  id:
    | '__root__'
    | '/'
    | '/account/'
    | '/help/'
    | '/message/'
    | '/organizations/'
    | '/premium/'
    | '/sign-in/'
    | '/sign-up/'
    | '/account/billing/'
    | '/found/$id/'
    | '/organizations/$slug/'
    | '/premium/checkout/'
    | '/premium/success/'
    | '/profile/$publicCode/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountIndexRoute: typeof AccountIndexRoute
  HelpIndexRoute: typeof HelpIndexRoute
  MessageIndexRoute: typeof MessageIndexRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  PremiumIndexRoute: typeof PremiumIndexRoute
  SignInIndexRoute: typeof SignInIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
  AccountBillingIndexRoute: typeof AccountBillingIndexRoute
  FoundIdIndexRoute: typeof FoundIdIndexRoute
  OrganizationsSlugIndexRoute: typeof OrganizationsSlugIndexRoute
  PremiumCheckoutIndexRoute: typeof PremiumCheckoutIndexRoute
  PremiumSuccessIndexRoute: typeof PremiumSuccessIndexRoute
  ProfilePublicCodeIndexRoute: typeof ProfilePublicCodeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium/': {
      id: '/premium/'
      path: '/premium'
      fullPath: '/premium/'
      preLoaderRoute: typeof PremiumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message/': {
      id: '/message/'
      path: '/message'
      fullPath: '/message/'
      preLoaderRoute: typeof MessageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$publicCode/': {
      id: '/profile/$publicCode/'
      path: '/profile/$publicCode'
      fullPath: '/profile/$publicCode/'
      preLoaderRoute: typeof ProfilePublicCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium/success/': {
      id: '/premium/success/'
      path: '/premium/success'
      fullPath: '/premium/success/'
      preLoaderRoute: typeof PremiumSuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium/checkout/': {
      id: '/premium/checkout/'
      path: '/premium/checkout'
      fullPath: '/premium/checkout/'
      preLoaderRoute: typeof PremiumCheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$slug/': {
      id: '/organizations/$slug/'
      path: '/organizations/$slug'
      fullPath: '/organizations/$slug/'
      preLoaderRoute: typeof OrganizationsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/found/$id/': {
      id: '/found/$id/'
      path: '/found/$id'
      fullPath: '/found/$id/'
      preLoaderRoute: typeof FoundIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/billing/': {
      id: '/account/billing/'
      path: '/account/billing'
      fullPath: '/account/billing/'
      preLoaderRoute: typeof AccountBillingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountIndexRoute: AccountIndexRoute,
  HelpIndexRoute: HelpIndexRoute,
  MessageIndexRoute: MessageIndexRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  PremiumIndexRoute: PremiumIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
  AccountBillingIndexRoute: AccountBillingIndexRoute,
  FoundIdIndexRoute: FoundIdIndexRoute,
  OrganizationsSlugIndexRoute: OrganizationsSlugIndexRoute,
  PremiumCheckoutIndexRoute: PremiumCheckoutIndexRoute,
  PremiumSuccessIndexRoute: PremiumSuccessIndexRoute,
  ProfilePublicCodeIndexRoute: ProfilePublicCodeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
