/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadIndexRouteImport } from './routes/download/index'
import { Route as ChatAnonymousRouteImport } from './routes/chat/anonymous'
import { Route as FoundIdIndexRouteImport } from './routes/found/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadIndexRoute = DownloadIndexRouteImport.update({
  id: '/download/',
  path: '/download/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatAnonymousRoute = ChatAnonymousRouteImport.update({
  id: '/chat/anonymous',
  path: '/chat/anonymous',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundIdIndexRoute = FoundIdIndexRouteImport.update({
  id: '/found/$id/',
  path: '/found/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat/anonymous': typeof ChatAnonymousRoute
  '/download': typeof DownloadIndexRoute
  '/found/$id': typeof FoundIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat/anonymous': typeof ChatAnonymousRoute
  '/download': typeof DownloadIndexRoute
  '/found/$id': typeof FoundIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat/anonymous': typeof ChatAnonymousRoute
  '/download/': typeof DownloadIndexRoute
  '/found/$id/': typeof FoundIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat/anonymous' | '/download' | '/found/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat/anonymous' | '/download' | '/found/$id'
  id: '__root__' | '/' | '/chat/anonymous' | '/download/' | '/found/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatAnonymousRoute: typeof ChatAnonymousRoute
  DownloadIndexRoute: typeof DownloadIndexRoute
  FoundIdIndexRoute: typeof FoundIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/': {
      id: '/download/'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/anonymous': {
      id: '/chat/anonymous'
      path: '/chat/anonymous'
      fullPath: '/chat/anonymous'
      preLoaderRoute: typeof ChatAnonymousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/found/$id/': {
      id: '/found/$id/'
      path: '/found/$id'
      fullPath: '/found/$id'
      preLoaderRoute: typeof FoundIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatAnonymousRoute: ChatAnonymousRoute,
  DownloadIndexRoute: DownloadIndexRoute,
  FoundIdIndexRoute: FoundIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
